

browser:
  default: "chrome"
  headless: false
  implicit_wait: 10
  page_load_timeout: 30


environments:
  #Your practice application url and credential
  practice:
    base_url: "http://49.249.28.218:8081/TestServer/Build/Small_CRM/admin/"
    username: "admin"
    password: "admin"

  # Your actual development environment
  dev:
    base_url: "https://dev.example.com"
    username: "dev_user"
    password: "dev_pass"

  # Your actual staging environment
  staging:
    base_url: "https://staging.example.com"
    username: "staging_user"
    password: "staging_pass"

  # Your actual production environment
  prod:
    base_url: "https://example.com"
    username: "prod_user"
    password: "prod_pass"